# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160921_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='timestamp',
            new_name='times',
        ),
    ]
