# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160921_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='times',
        ),
    ]
