# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_comments_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
